# Site settings
title: David Dvorak
subtitle: Personal Webpage
email: 
description: A place for me to showcase my work<br /> and share my thoughts.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://djdvorak.github.io" # the base hostname & protocol for your site
author: 
street_address: 
city: Vancouver
state: BC
zip_code: 
country: Canada
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 20

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/djdvorak
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/david-dvorak/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
